[package]
name = "evolution"
version = "0.0.1"
authors = [ "Jack" ]
edition="2018"



[dependencies]
ggez = "0.5.1"
gfx_core = "0.9"
gfx_device_gl = "0.16"
imgui = "0.2.1"
imgui-gfx-renderer = "0.2.0"
rand = "*"
nalgebra = "*"
simdeez = "*"
simdnoise = "3.1.2"
variant_count = "*"